[package]
name = "ray-tracing"
version = "0.1.0"
authors = ["seyoatda <seyoatda@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
